SET client_encoding = 'UTF8';

DO $$
DECLARE problems text; actual_hash text; bad integer;
BEGIN
    WITH expected(table_name,column_name,type_name,not_null) AS (
        VALUES
    ('companies','id','integer',true),
    ('companies','name','character varying(255)',true),
    ('companies','legal_address','text',false),
    ('companies','phone','character varying(50)',false),
    ('companies','email','character varying(255)',false),
    ('branches','id','integer',true),
    ('branches','company_id','integer',true),
    ('branches','name','character varying(255)',true),
    ('branches','legal_address','text',false),
    ('branches','phone','character varying(50)',false),
    ('branches','fax','character varying(50)',false),
    ('branches','email','character varying(255)',false),
    ('locations','id','integer',true),
    ('locations','branch_id','integer',true),
    ('locations','company_id','integer',false),
    ('locations','name','character varying(255)',true),
    ('locations','factual_address','text',false),
    ('locations','phone','character varying(50)',false),
    ('locations','email','character varying(255)',false),
    ('locations','fax','character varying(50)',false),
    ('doctors','id','integer',true),
    ('doctors','last_name','character varying(100)',true),
    ('doctors','first_name','character varying(100)',true),
    ('doctors','patronymic','character varying(100)',false),
    ('doctors','position','character varying(255)',false),
    ('doctors','initial_education','text',false),
    ('doctors','retraining_institution','text',false),
    ('doctors','certificate','text',false),
    ('doctors','qualification','text',false),
    ('doctors','phone','character varying(50)',false),
    ('doctor_locations','id','integer',true),
    ('doctor_locations','doctor_id','integer',true),
    ('doctor_locations','location_id','integer',true),
    ('patients','id','integer',true),
    ('patients','last_name','character varying(100)',true),
    ('patients','first_name','character varying(100)',true),
    ('patients','patronymic','character varying(100)',false),
    ('patients','birth_date','date',true),
    ('patients','gender','boolean',false),
    ('patients','phone','character varying(50)',false),
    ('patients','email','character varying(255)',false),
    ('users','id','integer',true),
    ('users','login','character varying(100)',true),
    ('users','password_hash','character varying(255)',true),
    ('users','role','character varying(20)',true),
    ('users','doctor_id','integer',false),
    ('users','patient_id','integer',false),
    ('appointments','id','integer',true),
    ('appointments','patient_id','integer',true),
    ('appointments','doctor_id','integer',true),
    ('appointments','location_id','integer',false),
    ('appointments','appointment_date','timestamp without time zone',true),
    ('appointments','age_at_appointment','smallint',true),
    ('surveys','id','integer',true),
    ('surveys','appointment_id','integer',true),
    ('surveys','complaints','text',false),
    ('surveys','education_and_professional_history','text',false),
    ('surveys','housing_conditions','text',false),
    ('surveys','past_diseases','text',false),
    ('surveys','habitual_intoxications','text',false),
    ('surveys','gynecological_history','text',false),
    ('surveys','heredity_description','text',false),
    ('surveys','family_life','text',false),
    ('surveys','allergological_history','text',false),
    ('surveys','epidemiological_history','text',false),
    ('surveys','insurance_history','text',false),
    ('surveys','disease_onset','text',false),
    ('surveys','disease_course','text',false),
    ('examinations','id','integer',true),
    ('examinations','appointment_id','integer',true),
    ('examinations','general_condition','character varying(30)',false),
    ('examinations','consciousness','character varying(30)',false),
    ('examinations','bed_position','character varying(30)',false),
    ('examinations','bed_position_details','text',false),
    ('examinations','body_build','text',false),
    ('examinations','height','numeric(5,2)',false),
    ('examinations','weight','numeric(5,2)',false),
    ('examinations','bmi','numeric(5,2)',false),
    ('examinations','constitution_type','character varying(30)',false),
    ('examinations','skin_and_mucous_membranes','text',false),
    ('examinations','edema_location','text',false),
    ('examinations','lymph_nodes','text',false),
    ('examinations','thyroid_gland','text',false),
    ('examinations','musculoskeletal_system','text',false),
    ('examinations','body_temperature','numeric(4,1)',false),
    ('examinations','systolic_pressure','integer',false),
    ('examinations','diastolic_pressure','integer',false),
    ('examinations','bp_note','text',false),
    ('examinations','heart_rate','integer',false),
    ('examinations','veins_condition','text',false),
    ('examinations','lung_auscultation','text',false),
    ('examinations','abdomen','text',false),
    ('examinations','kidney_palpation','character varying(30)',false),
    ('examinations','kidney_palpation_details','text',false),
    ('examinations','pasternatsky_result','character varying(20)',false),
    ('examinations','pasternatsky_side','character varying(20)',false),
    ('cbc_results','id','integer',true),
    ('cbc_results','appointment_id','integer',true),
    ('cbc_results','investigation_date','date',true),
    ('cbc_results','hemoglobin','numeric(6,2)',false),
    ('cbc_results','erythrocytes','numeric(6,2)',false),
    ('cbc_results','leukocytes','numeric(6,2)',false),
    ('cbc_results','platelets','numeric(7,2)',false),
    ('cbc_results','esr','numeric(6,2)',false),
    ('cbc_results','mcv','numeric(6,2)',false),
    ('cbc_results','hematocrit','numeric(6,2)',false),
    ('biochemistry_results','id','integer',true),
    ('biochemistry_results','appointment_id','integer',true),
    ('biochemistry_results','investigation_date','date',true),
    ('biochemistry_results','creatinine','numeric(8,2)',false),
    ('biochemistry_results','urea','numeric(8,2)',false),
    ('biochemistry_results','uric_acid','numeric(8,2)',false),
    ('biochemistry_results','glucose','numeric(6,2)',false),
    ('biochemistry_results','total_protein','numeric(6,2)',false),
    ('biochemistry_results','albumin','numeric(6,2)',false),
    ('biochemistry_results','potassium','numeric(5,2)',false),
    ('biochemistry_results','calcium','numeric(5,2)',false),
    ('biochemistry_results','phosphorus','numeric(5,2)',false),
    ('biochemistry_results','ferritin','numeric(8,2)',false),
    ('biochemistry_results','ptg','numeric(8,2)',false),
    ('urinalysis_results','id','integer',true),
    ('urinalysis_results','appointment_id','integer',true),
    ('urinalysis_results','investigation_date','date',true),
    ('urinalysis_results','specific_gravity','numeric(5,3)',false),
    ('urinalysis_results','protein','numeric(8,3)',false),
    ('urinalysis_results','leukocytes','numeric(8,2)',false),
    ('urinalysis_results','erythrocytes','numeric(8,2)',false),
    ('urinalysis_results','bacteria','character varying(100)',false),
    ('albuminuria_results','id','integer',true),
    ('albuminuria_results','appointment_id','integer',true),
    ('albuminuria_results','investigation_date','date',true),
    ('albuminuria_results','urine_albumin','numeric(10,3)',false),
    ('albuminuria_results','urine_albumin_unit','character varying(20)',true),
    ('albuminuria_results','urine_creatinine','numeric(10,3)',false),
    ('albuminuria_results','urine_creatinine_unit','character varying(20)',true),
    ('albuminuria_results','albumin_creatinine_ratio','numeric(10,2)',false),
    ('albuminuria_results','albuminuria_category','character varying(2)',false),
    ('albuminuria_results','daily_albumin_excretion','numeric(12,2)',false),
    ('albuminuria_results','created_at','timestamp without time zone',true),
    ('ultrasound_results','id','integer',true),
    ('ultrasound_results','appointment_id','integer',true),
    ('ultrasound_results','investigation_date','date',true),
    ('ultrasound_results','left_kidney_size','character varying(50)',false),
    ('ultrasound_results','right_kidney_size','character varying(50)',false),
    ('ultrasound_results','left_parenchyma','numeric(5,2)',false),
    ('ultrasound_results','right_parenchyma','numeric(5,2)',false),
    ('ultrasound_results','description','text',false),
    ('calculated_metrics','id','integer',true),
    ('calculated_metrics','appointment_id','integer',true),
    ('calculated_metrics','investigation_date','date',false),
    ('calculated_metrics','creatinine','numeric(8,2)',false),
    ('calculated_metrics','age','integer',false),
    ('calculated_metrics','gender','boolean',false),
    ('calculated_metrics','weight_at_appointment','numeric(5,2)',false),
    ('calculated_metrics','egfr_ckdepi','numeric(6,2)',false),
    ('calculated_metrics','crcl_cockcroft_gault','numeric(6,2)',false),
    ('calculated_metrics','ckd_stage','character varying(3)',false),
    ('calculated_metrics','calculation_date','timestamp without time zone',true),
    ('ckd_prognosis_results','id','integer',true),
    ('ckd_prognosis_results','appointment_id','integer',true),
    ('ckd_prognosis_results','assessment_date','date',true),
    ('ckd_prognosis_results','gfr_category','character varying(3)',false),
    ('ckd_prognosis_results','albuminuria_category','character varying(2)',false),
    ('ckd_prognosis_results','combined_category','character varying(8)',false),
    ('ckd_prognosis_results','prognosis_level','character varying(20)',false),
    ('ckd_prognosis_results','prognosis_text','character varying(100)',false),
    ('ckd_prognosis_results','gfr_metric_id','integer',false),
    ('ckd_prognosis_results','albuminuria_result_id','integer',false),
    ('ckd_prognosis_results','gfr_investigation_date','date',false),
    ('ckd_prognosis_results','albuminuria_investigation_date','date',false),
    ('ckd_prognosis_results','gfr_source_type','character varying(30)',false),
    ('ckd_prognosis_results','albuminuria_source_type','character varying(30)',false),
    ('ckd_prognosis_results','source_interval_days','integer',false),
    ('ckd_prognosis_results','calculation_status','character varying(30)',true),
    ('ckd_prognosis_results','display_order','integer',true),
    ('ckd_prognosis_results','is_active','boolean',true),
    ('ckd_prognosis_results','hidden_at','timestamp without time zone',false),
    ('ckd_prognosis_results','hidden_reason','text',false),
    ('ckd_prognosis_results','created_at','timestamp without time zone',true),
    ('ckd_prognosis_results','updated_at','timestamp without time zone',true),
    ('appointment_diets','id','integer',true),
    ('appointment_diets','appointment_id','integer',true),
    ('appointment_diets','diet','text',false),
    ('appointment_diets','next_control_date','date',false),
    ('appointment_diets','recommendations','text',false),
    ('prescriptions','id','integer',true),
    ('prescriptions','appointment_id','integer',true),
    ('prescriptions','medication','character varying(255)',false),
    ('prescriptions','dosage','character varying(100)',false),
    ('prescriptions','schedule','character varying(255)',false),
    ('prescriptions','therapy_group','character varying(64)',false),
    ('icd10_diagnoses','id','integer',true),
    ('icd10_diagnoses','diagnosis','text',true),
    ('icd10_diagnoses','is_active','boolean',true),
    ('icd10_diagnoses','sort_order','integer',false),
    ('icd10_diagnoses','created_at','timestamp without time zone',true),
    ('icd10_diagnoses','updated_at','timestamp without time zone',true),
    ('appointment_icd10_diagnoses','id','integer',true),
    ('appointment_icd10_diagnoses','appointment_id','integer',true),
    ('appointment_icd10_diagnoses','diagnosis_type','character varying(20)',true),
    ('appointment_icd10_diagnoses','icd10_diagnosis_id','integer',true),
    ('appointment_icd10_diagnoses','doctor_note','text',false),
    ('appointment_icd10_diagnoses','sort_order','integer',true),
    ('appointment_icd10_diagnoses','created_at','timestamp without time zone',true),
    ('appointment_icd10_diagnoses','updated_at','timestamp without time zone',true),
    ('medications','id','integer',true),
    ('medications','display_name','character varying(255)',true),
    ('medications','trade_name','character varying(255)',false),
    ('medications','active_substance','character varying(255)',false),
    ('medications','drug_group','character varying(255)',false),
    ('medications','sort_order','integer',true),
    ('medications','is_active','boolean',true),
    ('medications','created_at','timestamp without time zone',true),
    ('medications','updated_at','timestamp without time zone',true),
    ('appointment_additional_studies','appointment_id','integer',true),
    ('appointment_additional_studies','other_laboratory_studies','text',false),
    ('appointment_additional_studies','other_instrumental_studies','text',false),
    ('audit_events','id','bigint',true),
    ('audit_events','created_at','timestamp with time zone',true),
    ('audit_events','user_id','integer',false),
    ('audit_events','user_login','text',false),
    ('audit_events','user_role','character varying(50)',false),
    ('audit_events','action','character varying(100)',true),
    ('audit_events','result','character varying(30)',true),
    ('audit_events','patient_id','integer',false),
    ('audit_events','appointment_id','integer',false),
    ('audit_events','entity_type','character varying(100)',false),
    ('audit_events','entity_id','integer',false),
    ('audit_events','ip_address','inet',false),
    ('audit_events','path','text',false),
    ('audit_events','method','character varying(10)',false),
    ('audit_events','status_code','integer',false),
    ('audit_events','details','text',false),
    ('audit_events','error_message','text',false),
    ('audit_event_changes','id','integer',true),
    ('audit_event_changes','audit_event_id','integer',true),
    ('audit_event_changes','section','character varying(100)',true),
    ('audit_event_changes','section_label','character varying(255)',true),
    ('audit_event_changes','field_name','character varying(100)',false),
    ('audit_event_changes','field_label','character varying(255)',false),
    ('audit_event_changes','change_type','character varying(60)',true),
    ('audit_event_changes','old_value','text',false),
    ('audit_event_changes','new_value','text',false),
    ('audit_event_changes','details','text',false),
    ('audit_event_changes','sort_order','integer',true),
    ('audit_event_changes','created_at','timestamp with time zone',true),
    ('schedule_entries','id','integer',true),
    ('schedule_entries','scheduled_doctor_id','integer',true),
    ('schedule_entries','location_id','integer',true),
    ('schedule_entries','patient_id','integer',true),
    ('schedule_entries','starts_at','timestamp without time zone',true),
    ('schedule_entries','ends_at','timestamp without time zone',true),
    ('schedule_entries','appointment_type','character varying(20)',true),
    ('schedule_entries','status','character varying(20)',true),
    ('schedule_entries','actual_doctor_id','integer',false),
    ('schedule_entries','appointment_id','integer',false),
    ('schedule_entries','note','text',false),
    ('schedule_entries','created_by_user_id','integer',false),
    ('schedule_entries','created_at','timestamp without time zone',true),
    ('schedule_entries','updated_at','timestamp without time zone',true),
    ('schedule_entries','cancelled_at','timestamp without time zone',false),
    ('schedule_entries','cancelled_by_user_id','integer',false),
    ('schedule_entries','cancel_reason','text',false),
    ('ckd_registry_entries','id','bigint',true),
    ('ckd_registry_entries','patient_id','integer',true),
    ('ckd_registry_entries','included_at','date',true),
    ('ckd_registry_entries','included_by_user_id','integer',false),
    ('ckd_registry_entries','diagnosis_at_inclusion','text',true),
    ('ckd_registry_entries','egfr_at_inclusion','numeric(6,2)',false),
    ('ckd_registry_entries','ckd_stage_at_inclusion','character varying(3)',false),
    ('ckd_registry_entries','comment_at_inclusion','text',false),
    ('ckd_registry_entries','is_active','boolean',true),
    ('ckd_registry_entries','closed_at','date',false),
    ('ckd_registry_entries','closed_by_user_id','integer',false),
    ('ckd_registry_entries','close_reason','text',false),
    ('ckd_registry_entries','created_at','timestamp with time zone',true),
    ('ckd_registry_entries','updated_at','timestamp with time zone',true),
    ('ckd_registry_outcomes','id','bigint',true),
    ('ckd_registry_outcomes','registry_entry_id','bigint',true),
    ('ckd_registry_outcomes','outcome_type','character varying(40)',true),
    ('ckd_registry_outcomes','outcome_date','date',true),
    ('ckd_registry_outcomes','comment','text',false),
    ('ckd_registry_outcomes','created_by_user_id','integer',false),
    ('ckd_registry_outcomes','created_at','timestamp with time zone',true)
    )
    SELECT string_agg(e.table_name||'.'||e.column_name||' ['||
        CASE WHEN a.attname IS NULL THEN 'нет столбца'
             ELSE format_type(a.atttypid,a.atttypmod)||', nullable='||NOT a.attnotnull END||']', E'\n')
      INTO problems
      FROM expected e
      LEFT JOIN pg_class c ON c.relname=e.table_name
      LEFT JOIN pg_namespace n ON n.oid=c.relnamespace AND n.nspname='public'
      LEFT JOIN pg_attribute a ON a.attrelid=c.oid AND a.attname=e.column_name AND a.attnum>0 AND NOT a.attisdropped
     WHERE a.attname IS NULL OR format_type(a.atttypid,a.atttypmod)<>e.type_name OR a.attnotnull<>e.not_null;
    IF problems IS NOT NULL THEN RAISE EXCEPTION 'Несоответствие столбцов:%',E'\n'||problems; END IF;

    WITH expected(table_name,column_name) AS (
        VALUES
    ('companies','id'),
    ('companies','name'),
    ('companies','legal_address'),
    ('companies','phone'),
    ('companies','email'),
    ('branches','id'),
    ('branches','company_id'),
    ('branches','name'),
    ('branches','legal_address'),
    ('branches','phone'),
    ('branches','fax'),
    ('branches','email'),
    ('locations','id'),
    ('locations','branch_id'),
    ('locations','company_id'),
    ('locations','name'),
    ('locations','factual_address'),
    ('locations','phone'),
    ('locations','email'),
    ('locations','fax'),
    ('doctors','id'),
    ('doctors','last_name'),
    ('doctors','first_name'),
    ('doctors','patronymic'),
    ('doctors','position'),
    ('doctors','initial_education'),
    ('doctors','retraining_institution'),
    ('doctors','certificate'),
    ('doctors','qualification'),
    ('doctors','phone'),
    ('doctor_locations','id'),
    ('doctor_locations','doctor_id'),
    ('doctor_locations','location_id'),
    ('patients','id'),
    ('patients','last_name'),
    ('patients','first_name'),
    ('patients','patronymic'),
    ('patients','birth_date'),
    ('patients','gender'),
    ('patients','phone'),
    ('patients','email'),
    ('users','id'),
    ('users','login'),
    ('users','password_hash'),
    ('users','role'),
    ('users','doctor_id'),
    ('users','patient_id'),
    ('appointments','id'),
    ('appointments','patient_id'),
    ('appointments','doctor_id'),
    ('appointments','location_id'),
    ('appointments','appointment_date'),
    ('appointments','age_at_appointment'),
    ('surveys','id'),
    ('surveys','appointment_id'),
    ('surveys','complaints'),
    ('surveys','education_and_professional_history'),
    ('surveys','housing_conditions'),
    ('surveys','past_diseases'),
    ('surveys','habitual_intoxications'),
    ('surveys','gynecological_history'),
    ('surveys','heredity_description'),
    ('surveys','family_life'),
    ('surveys','allergological_history'),
    ('surveys','epidemiological_history'),
    ('surveys','insurance_history'),
    ('surveys','disease_onset'),
    ('surveys','disease_course'),
    ('examinations','id'),
    ('examinations','appointment_id'),
    ('examinations','general_condition'),
    ('examinations','consciousness'),
    ('examinations','bed_position'),
    ('examinations','bed_position_details'),
    ('examinations','body_build'),
    ('examinations','height'),
    ('examinations','weight'),
    ('examinations','bmi'),
    ('examinations','constitution_type'),
    ('examinations','skin_and_mucous_membranes'),
    ('examinations','edema_location'),
    ('examinations','lymph_nodes'),
    ('examinations','thyroid_gland'),
    ('examinations','musculoskeletal_system'),
    ('examinations','body_temperature'),
    ('examinations','systolic_pressure'),
    ('examinations','diastolic_pressure'),
    ('examinations','bp_note'),
    ('examinations','heart_rate'),
    ('examinations','veins_condition'),
    ('examinations','lung_auscultation'),
    ('examinations','abdomen'),
    ('examinations','kidney_palpation'),
    ('examinations','kidney_palpation_details'),
    ('examinations','pasternatsky_result'),
    ('examinations','pasternatsky_side'),
    ('cbc_results','id'),
    ('cbc_results','appointment_id'),
    ('cbc_results','investigation_date'),
    ('cbc_results','hemoglobin'),
    ('cbc_results','erythrocytes'),
    ('cbc_results','leukocytes'),
    ('cbc_results','platelets'),
    ('cbc_results','esr'),
    ('cbc_results','mcv'),
    ('cbc_results','hematocrit'),
    ('biochemistry_results','id'),
    ('biochemistry_results','appointment_id'),
    ('biochemistry_results','investigation_date'),
    ('biochemistry_results','creatinine'),
    ('biochemistry_results','urea'),
    ('biochemistry_results','uric_acid'),
    ('biochemistry_results','glucose'),
    ('biochemistry_results','total_protein'),
    ('biochemistry_results','albumin'),
    ('biochemistry_results','potassium'),
    ('biochemistry_results','calcium'),
    ('biochemistry_results','phosphorus'),
    ('biochemistry_results','ferritin'),
    ('biochemistry_results','ptg'),
    ('urinalysis_results','id'),
    ('urinalysis_results','appointment_id'),
    ('urinalysis_results','investigation_date'),
    ('urinalysis_results','specific_gravity'),
    ('urinalysis_results','protein'),
    ('urinalysis_results','leukocytes'),
    ('urinalysis_results','erythrocytes'),
    ('urinalysis_results','bacteria'),
    ('albuminuria_results','id'),
    ('albuminuria_results','appointment_id'),
    ('albuminuria_results','investigation_date'),
    ('albuminuria_results','urine_albumin'),
    ('albuminuria_results','urine_albumin_unit'),
    ('albuminuria_results','urine_creatinine'),
    ('albuminuria_results','urine_creatinine_unit'),
    ('albuminuria_results','albumin_creatinine_ratio'),
    ('albuminuria_results','albuminuria_category'),
    ('albuminuria_results','daily_albumin_excretion'),
    ('albuminuria_results','created_at'),
    ('ultrasound_results','id'),
    ('ultrasound_results','appointment_id'),
    ('ultrasound_results','investigation_date'),
    ('ultrasound_results','left_kidney_size'),
    ('ultrasound_results','right_kidney_size'),
    ('ultrasound_results','left_parenchyma'),
    ('ultrasound_results','right_parenchyma'),
    ('ultrasound_results','description'),
    ('calculated_metrics','id'),
    ('calculated_metrics','appointment_id'),
    ('calculated_metrics','investigation_date'),
    ('calculated_metrics','creatinine'),
    ('calculated_metrics','age'),
    ('calculated_metrics','gender'),
    ('calculated_metrics','weight_at_appointment'),
    ('calculated_metrics','egfr_ckdepi'),
    ('calculated_metrics','crcl_cockcroft_gault'),
    ('calculated_metrics','ckd_stage'),
    ('calculated_metrics','calculation_date'),
    ('ckd_prognosis_results','id'),
    ('ckd_prognosis_results','appointment_id'),
    ('ckd_prognosis_results','assessment_date'),
    ('ckd_prognosis_results','gfr_category'),
    ('ckd_prognosis_results','albuminuria_category'),
    ('ckd_prognosis_results','combined_category'),
    ('ckd_prognosis_results','prognosis_level'),
    ('ckd_prognosis_results','prognosis_text'),
    ('ckd_prognosis_results','gfr_metric_id'),
    ('ckd_prognosis_results','albuminuria_result_id'),
    ('ckd_prognosis_results','gfr_investigation_date'),
    ('ckd_prognosis_results','albuminuria_investigation_date'),
    ('ckd_prognosis_results','gfr_source_type'),
    ('ckd_prognosis_results','albuminuria_source_type'),
    ('ckd_prognosis_results','source_interval_days'),
    ('ckd_prognosis_results','calculation_status'),
    ('ckd_prognosis_results','display_order'),
    ('ckd_prognosis_results','is_active'),
    ('ckd_prognosis_results','hidden_at'),
    ('ckd_prognosis_results','hidden_reason'),
    ('ckd_prognosis_results','created_at'),
    ('ckd_prognosis_results','updated_at'),
    ('appointment_diets','id'),
    ('appointment_diets','appointment_id'),
    ('appointment_diets','diet'),
    ('appointment_diets','next_control_date'),
    ('appointment_diets','recommendations'),
    ('prescriptions','id'),
    ('prescriptions','appointment_id'),
    ('prescriptions','medication'),
    ('prescriptions','dosage'),
    ('prescriptions','schedule'),
    ('prescriptions','therapy_group'),
    ('icd10_diagnoses','id'),
    ('icd10_diagnoses','diagnosis'),
    ('icd10_diagnoses','is_active'),
    ('icd10_diagnoses','sort_order'),
    ('icd10_diagnoses','created_at'),
    ('icd10_diagnoses','updated_at'),
    ('appointment_icd10_diagnoses','id'),
    ('appointment_icd10_diagnoses','appointment_id'),
    ('appointment_icd10_diagnoses','diagnosis_type'),
    ('appointment_icd10_diagnoses','icd10_diagnosis_id'),
    ('appointment_icd10_diagnoses','doctor_note'),
    ('appointment_icd10_diagnoses','sort_order'),
    ('appointment_icd10_diagnoses','created_at'),
    ('appointment_icd10_diagnoses','updated_at'),
    ('medications','id'),
    ('medications','display_name'),
    ('medications','trade_name'),
    ('medications','active_substance'),
    ('medications','drug_group'),
    ('medications','sort_order'),
    ('medications','is_active'),
    ('medications','created_at'),
    ('medications','updated_at'),
    ('appointment_additional_studies','appointment_id'),
    ('appointment_additional_studies','other_laboratory_studies'),
    ('appointment_additional_studies','other_instrumental_studies'),
    ('audit_events','id'),
    ('audit_events','created_at'),
    ('audit_events','user_id'),
    ('audit_events','user_login'),
    ('audit_events','user_role'),
    ('audit_events','action'),
    ('audit_events','result'),
    ('audit_events','patient_id'),
    ('audit_events','appointment_id'),
    ('audit_events','entity_type'),
    ('audit_events','entity_id'),
    ('audit_events','ip_address'),
    ('audit_events','path'),
    ('audit_events','method'),
    ('audit_events','status_code'),
    ('audit_events','details'),
    ('audit_events','error_message'),
    ('audit_event_changes','id'),
    ('audit_event_changes','audit_event_id'),
    ('audit_event_changes','section'),
    ('audit_event_changes','section_label'),
    ('audit_event_changes','field_name'),
    ('audit_event_changes','field_label'),
    ('audit_event_changes','change_type'),
    ('audit_event_changes','old_value'),
    ('audit_event_changes','new_value'),
    ('audit_event_changes','details'),
    ('audit_event_changes','sort_order'),
    ('audit_event_changes','created_at'),
    ('schedule_entries','id'),
    ('schedule_entries','scheduled_doctor_id'),
    ('schedule_entries','location_id'),
    ('schedule_entries','patient_id'),
    ('schedule_entries','starts_at'),
    ('schedule_entries','ends_at'),
    ('schedule_entries','appointment_type'),
    ('schedule_entries','status'),
    ('schedule_entries','actual_doctor_id'),
    ('schedule_entries','appointment_id'),
    ('schedule_entries','note'),
    ('schedule_entries','created_by_user_id'),
    ('schedule_entries','created_at'),
    ('schedule_entries','updated_at'),
    ('schedule_entries','cancelled_at'),
    ('schedule_entries','cancelled_by_user_id'),
    ('schedule_entries','cancel_reason'),
    ('ckd_registry_entries','id'),
    ('ckd_registry_entries','patient_id'),
    ('ckd_registry_entries','included_at'),
    ('ckd_registry_entries','included_by_user_id'),
    ('ckd_registry_entries','diagnosis_at_inclusion'),
    ('ckd_registry_entries','egfr_at_inclusion'),
    ('ckd_registry_entries','ckd_stage_at_inclusion'),
    ('ckd_registry_entries','comment_at_inclusion'),
    ('ckd_registry_entries','is_active'),
    ('ckd_registry_entries','closed_at'),
    ('ckd_registry_entries','closed_by_user_id'),
    ('ckd_registry_entries','close_reason'),
    ('ckd_registry_entries','created_at'),
    ('ckd_registry_entries','updated_at'),
    ('ckd_registry_outcomes','id'),
    ('ckd_registry_outcomes','registry_entry_id'),
    ('ckd_registry_outcomes','outcome_type'),
    ('ckd_registry_outcomes','outcome_date'),
    ('ckd_registry_outcomes','comment'),
    ('ckd_registry_outcomes','created_by_user_id'),
    ('ckd_registry_outcomes','created_at')
    )
    SELECT string_agg(c.relname||'.'||a.attname,', ')
      INTO problems
      FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
      JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped
      LEFT JOIN expected e ON e.table_name=c.relname AND e.column_name=a.attname
     WHERE n.nspname='public' AND c.relkind='r' AND e.column_name IS NULL;
    IF problems IS NOT NULL THEN RAISE EXCEPTION 'Лишние столбцы: %',problems; END IF;

    SELECT string_agg(table_name,', ') INTO problems
      FROM information_schema.tables
     WHERE table_schema='public' AND table_type='BASE TABLE' AND table_name NOT IN ('companies', 'branches', 'locations', 'doctors', 'doctor_locations', 'patients', 'users', 'appointments', 'surveys', 'examinations', 'cbc_results', 'biochemistry_results', 'urinalysis_results', 'albuminuria_results', 'ultrasound_results', 'calculated_metrics', 'ckd_prognosis_results', 'appointment_diets', 'prescriptions', 'icd10_diagnoses', 'appointment_icd10_diagnoses', 'medications', 'appointment_additional_studies', 'audit_events', 'audit_event_changes', 'schedule_entries', 'ckd_registry_entries', 'ckd_registry_outcomes');
    IF problems IS NOT NULL THEN RAISE EXCEPTION 'Лишние таблицы core: %',problems; END IF;

    WITH expected(name) AS (VALUES ('chk_albuminuria_category'), ('chk_albuminuria_units'), ('chk_albuminuria_values'), ('chk_appointment_icd10_diagnoses_type'), ('chk_appointments_age_at_appointment'), ('chk_appointments_not_future'), ('chk_biochemistry_non_negative'), ('chk_calculated_metrics_ckd_stage'), ('chk_calculated_metrics_values'), ('chk_cbc_non_negative'), ('chk_ckd_prognosis_calculated_sources'), ('chk_ckd_prognosis_categories'), ('chk_ckd_prognosis_combined_category'), ('chk_ckd_prognosis_source_interval'), ('chk_examinations_anthropometry'), ('chk_examinations_bed_position'), ('chk_examinations_bed_position_details'), ('chk_examinations_body_temperature'), ('chk_examinations_bp'), ('chk_examinations_consciousness'), ('chk_examinations_constitution_type'), ('chk_examinations_general_condition'), ('chk_examinations_heart_rate'), ('chk_examinations_kidney_palpation'), ('chk_examinations_kidney_palpation_details'), ('chk_examinations_pasternatsky_pair'), ('chk_examinations_pasternatsky_result'), ('chk_examinations_pasternatsky_side'), ('chk_patients_birth_date_reasonable'), ('chk_ultrasound_values'), ('chk_urinalysis_non_negative'), ('chk_users_role_model'), ('ck_albuminuria_daily_albumin_excretion_nonnegative'), ('ck_audit_events_result'), ('ck_ckd_registry_entries_closure'), ('ck_ckd_registry_entries_egfr_non_negative'), ('ck_ckd_registry_entries_stage'), ('ck_ckd_registry_outcomes_date_not_future'), ('ck_ckd_registry_outcomes_type'), ('ck_prescriptions_therapy_group'), ('ck_schedule_entries_appointment_type'), ('ck_schedule_entries_status'), ('ck_schedule_entries_time'), ('fk_albuminuria_appointment'), ('fk_appointment_additional_studies_appointment'), ('fk_appointment_diets_appointment'), ('fk_appointment_icd10_diagnoses_appointment'), ('fk_appointment_icd10_diagnoses_icd10'), ('fk_appointments_doctor'), ('fk_appointments_location'), ('fk_appointments_patient'), ('fk_audit_event_changes_event'), ('fk_audit_events_appointment'), ('fk_audit_events_patient'), ('fk_audit_events_user'), ('fk_biochemistry_appointment'), ('fk_branches_company'), ('fk_calculated_metrics_appointment'), ('fk_cbc_appointment'), ('fk_ckd_prognosis_albuminuria_result'), ('fk_ckd_prognosis_appointment'), ('fk_ckd_prognosis_gfr_metric'), ('fk_ckd_registry_entries_closed_by'), ('fk_ckd_registry_entries_included_by'), ('fk_ckd_registry_entries_patient'), ('fk_ckd_registry_outcomes_created_by'), ('fk_ckd_registry_outcomes_entry'), ('fk_doctor_locations_doctor'), ('fk_doctor_locations_location'), ('fk_examinations_appointment'), ('fk_locations_branch'), ('fk_locations_company'), ('fk_prescriptions_appointment'), ('fk_schedule_entries_actual_doctor'), ('fk_schedule_entries_appointment'), ('fk_schedule_entries_cancelled_by'), ('fk_schedule_entries_created_by'), ('fk_schedule_entries_location'), ('fk_schedule_entries_patient'), ('fk_schedule_entries_scheduled_doctor'), ('fk_surveys_appointment'), ('fk_ultrasound_appointment'), ('fk_urinalysis_appointment'), ('fk_users_doctor'), ('fk_users_patient'), ('uq_appointment_diets_appointment'), ('uq_appointment_icd10_diagnoses_position'), ('uq_ckd_registry_entries_patient'), ('uq_doctor_locations_pair'), ('uq_examinations_appointment'), ('uq_icd10_diagnoses_diagnosis'), ('uq_medications_display_name'), ('uq_surveys_appointment'), ('uq_users_login'))
    SELECT string_agg(e.name,', ') INTO problems FROM expected e
      LEFT JOIN pg_constraint c ON c.conname=e.name WHERE c.oid IS NULL;
    IF problems IS NOT NULL THEN RAISE EXCEPTION 'Не созданы ограничения: %',problems; END IF;

    WITH expected(name) AS (VALUES ('idx_albuminuria_appointment_date'), ('idx_albuminuria_appointment_id'), ('idx_appointment_diets_appointment_id'), ('idx_appointment_icd10_diagnoses_appointment_id'), ('idx_appointment_icd10_diagnoses_icd10_id'), ('idx_appointment_icd10_diagnoses_type'), ('idx_appointments_date'), ('idx_appointments_doctor_id'), ('idx_appointments_location_id'), ('idx_appointments_patient_date'), ('idx_appointments_patient_id'), ('idx_biochemistry_appointment_date'), ('idx_biochemistry_appointment_id'), ('idx_branches_company_id'), ('idx_calculated_metrics_appointment_date'), ('idx_calculated_metrics_appointment_id'), ('idx_cbc_appointment_date'), ('idx_cbc_appointment_id'), ('idx_ckd_prognosis_albuminuria_date'), ('idx_ckd_prognosis_appointment_id'), ('idx_ckd_prognosis_assessment_active'), ('idx_ckd_prognosis_assessment_date'), ('idx_ckd_prognosis_gfr_date'), ('idx_ckd_prognosis_matrix_lookup'), ('idx_doctor_locations_doctor_id'), ('idx_doctor_locations_location_id'), ('idx_examinations_appointment_id'), ('idx_icd10_diagnoses_active'), ('idx_icd10_diagnoses_sort_order'), ('idx_icd10_diagnoses_text'), ('idx_locations_branch_id'), ('idx_medications_active_substance'), ('idx_medications_is_active'), ('idx_medications_sort_order'), ('idx_patients_fio'), ('idx_prescriptions_appointment_id'), ('idx_prescriptions_therapy_group'), ('idx_surveys_appointment_id'), ('idx_ultrasound_appointment_date'), ('idx_ultrasound_appointment_id'), ('idx_urinalysis_appointment_date'), ('idx_urinalysis_appointment_id'), ('ix_audit_event_changes_event_id'), ('ix_audit_event_changes_section'), ('ix_audit_event_changes_type'), ('ix_audit_events_action'), ('ix_audit_events_appointment_id'), ('ix_audit_events_created_at'), ('ix_audit_events_patient_id'), ('ix_audit_events_result'), ('ix_audit_events_user_id'), ('ix_ckd_registry_entries_included_at'), ('ix_ckd_registry_entries_is_active'), ('ix_ckd_registry_outcomes_entry_date'), ('ix_ckd_registry_outcomes_type'), ('ix_schedule_entries_doctor_period'), ('ix_schedule_entries_location_period'), ('ix_schedule_entries_patient'), ('ix_schedule_entries_status'), ('uq_ckd_prognosis_active_source_pair'), ('ux_schedule_entries_appointment'))
    SELECT string_agg(e.name,', ') INTO problems FROM expected e
      LEFT JOIN pg_indexes i ON i.schemaname='public' AND i.indexname=e.name WHERE i.indexname IS NULL;
    IF problems IS NOT NULL THEN RAISE EXCEPTION 'Не созданы индексы: %',problems; END IF;

    IF (SELECT array_agg(column_name::text ORDER BY ordinal_position) FROM information_schema.columns
        WHERE table_schema='public' AND table_name='appointment_icd10_diagnoses_view')
       IS DISTINCT FROM ARRAY['id','appointment_id','diagnosis_type','icd10_diagnosis_id','icd10_diagnosis','doctor_note','sort_order','created_at','updated_at']::text[]
    THEN RAISE EXCEPTION 'Неверна структура appointment_icd10_diagnoses_view'; END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
                   WHERE n.nspname='public' AND p.proname='set_ckd_prognosis_source_fields')
    THEN RAISE EXCEPTION 'Не создана функция KDIGO'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_set_ckd_prognosis_source_fields' AND NOT tgisinternal)
    THEN RAISE EXCEPTION 'Не создан триггер KDIGO'; END IF;

    SELECT count(*) INTO bad FROM medications; IF bad<>27 THEN RAISE EXCEPTION 'Ожидалось 27 лекарств, получено %',bad; END IF;
    SELECT md5(string_agg(display_name||E'\t'||COALESCE(trade_name,'<NULL>')||E'\t'||COALESCE(active_substance,'<NULL>')||E'\t'||COALESCE(drug_group,'<NULL>')||E'\t'||sort_order::text||E'\t'||is_active::text,E'\n' ORDER BY sort_order,display_name)) INTO actual_hash FROM medications;
    IF actual_hash<>'f354df73c0220018dc863d7e62971b1b' THEN RAISE EXCEPTION 'Изменён справочник лекарств: %',actual_hash; END IF;

    SELECT count(*) INTO bad FROM icd10_diagnoses; IF bad<>155 THEN RAISE EXCEPTION 'Ожидалось 155 записей МКБ, получено %',bad; END IF;
    SELECT md5(string_agg(diagnosis||E'\t'||sort_order::text||E'\t'||is_active::text,E'\n' ORDER BY sort_order,diagnosis)) INTO actual_hash FROM icd10_diagnoses;
    IF actual_hash<>'4e22e7697991d229dfa549663337d4fd' THEN RAISE EXCEPTION 'Изменён справочник МКБ: %',actual_hash; END IF;

    IF (SELECT count(*) FROM companies)<>2 OR (SELECT count(*) FROM branches)<>3 OR (SELECT count(*) FROM locations)<>7 OR (SELECT count(*) FROM doctors)<>12
    THEN RAISE EXCEPTION 'Неверно загружен справочник больницы'; END IF;
    SELECT count(*) INTO bad FROM users WHERE role='registrar' AND login='registrar' AND doctor_id IS NULL AND patient_id IS NULL;
    IF bad<>1 THEN RAISE EXCEPTION 'Не создан регистратор'; END IF;
    IF EXISTS (SELECT 1 FROM users WHERE role='patient') THEN RAISE EXCEPTION 'Роль patient не должна использоваться'; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='chk_users_role_model' AND pg_get_constraintdef(oid) LIKE '%registrar%' AND POSITION('''patient''' IN pg_get_constraintdef(oid))=0)
    THEN RAISE EXCEPTION 'Не установлена новая ролевая модель'; END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='appointments' AND column_name IN ('archive_import_key','archive_source_relative_path','diagnosis_text','diagnosis_comment_text','is_archive_import'))
    THEN RAISE EXCEPTION 'Архивные поля попали в core'; END IF;
END $$;
SELECT 'core_v2_ok' AS result;
